/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppReplayRouteImport } from './routes/_app.replay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppReplayRoute = AppReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pipeline': typeof AppPipelineRoute
  '/replay': typeof AppReplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pipeline': typeof AppPipelineRoute
  '/replay': typeof AppReplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/replay': typeof AppReplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pipeline' | '/replay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pipeline' | '/replay'
  id: '__root__' | '/' | '/_app' | '/_app/pipeline' | '/_app/replay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/replay': {
      id: '/_app/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof AppReplayRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppPipelineRoute: typeof AppPipelineRoute
  AppReplayRoute: typeof AppReplayRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPipelineRoute: AppPipelineRoute,
  AppReplayRoute: AppReplayRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
